### PR TITLE
Updated contact info in contact page and fixed typo

### PR DESCRIPTION
**Pull request by priyanka1110**
## Description
This PR fixes the Issue - [Bangalore address is not updated](https://github.com/Infratab/Website-IN/issues/25) and [Minor bugs in website](https://github.com/Infratab/Website-IN/issues/28)

# Implementation
***Contact info in the contact page***

Updated the Bangalore office address and contact information in the contact page.

NOTE: Office phone number has been removed temporarily from the footer and address the websites as currently, we don't have.

From : 
```
Infratab Bangalore Pvt Ltd
#20, 24th Main Road
2nd Phase, JP Nagar,
Bangalore - 560078,
Karnataka, India

(+91) 80 4092 9250

careers@infratab.in 
```
To: 
```
 Infratab Bangalore Pvt Ltd
 Cowrks, Building 6A,
 RMZ Eco World, Outer Ring Rd,
 Devarabisanahalli, Bellandur, 
 Bengaluru, Karnataka 560103

 info@infratab.in 
```
***Fix typo***
- Fixed typo with contact page title from `Infratab | conatct` to `Infratab | Contact`.

***Footer***
- Removed `infratab.com` website URL as it was not needed there.

## Screenshots
*Address*
in-contact

*Fix typo*
title

*Footer (without a phone number & infratab.com URL )**
footer

## Related PRs/Issues
List related PRs against other branches:

Issue Title | PR URL
-------|-----
Bangalore address is not updated | #25 
Minor bugs in website | #28 

## Impacted Areas
List related PRs from other repositories
- No impact on other repositories

List expected works in other repositories
- No work in other repositories

### Checklist
- [x] Set proper milestone and labels
- [x] Code compiles correctly
- [x] Lint pass locally with my changes
- [x] Extended the README/documentation as necessary
- [x] Test Summary - https://infratab.atlassian.net/wiki/spaces/TC/pages/277643303/27+Updated+the+bangalore+office+address

### CODE REVIEW

**Review by rahulkarkera — APPROVED** [review]
LGTM

**Review by prabhumarappan — COMMENTED** [review]
@moosicalbovine @priyanka0901 In the contact us page, the email ID given is for the careers. The page title suggests something and when you scroll down it says "Looking for an Opportunity?".

**Comment by priyanka1110** [comment]
@prabhumarappan Checked the design the email ID `careers` is a typo and it should be `info@infratab.in`

**Comment by prabhumarappan** [comment]
@priyanka1110 Spelling mistake with the page Title, "Infratab | Conatct" -> "Infratab | Contact"

**Comment by rahulkarkera** [comment]
@priyanka1110 There's no issue linked for typo and footer fixes.

**Comment by priyanka1110** [comment]
@rhlk92 I have updated the PR descriptions. Please check.

**Review by prabhumarappan — APPROVED** [review]

**Review by rahulkarkera — APPROVED** [review]
LGTM

**Review by moosicalbovine — APPROVED** [review]

**Pull request merged**
